linters:
  disable-all: true
  enable:
    - asciicheck
    - deadcode
    - exhaustive
    - exportloopref
    - goconst
    - goimports
    - gofmt # redundant, since gofmt *should* be a no-op after gofumpt
    - gofumpt
    - gosimple
    - ineffassign
    - misspell
    - prealloc
    - scopelint
    - staticcheck
    - stylecheck
    - structcheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - vet
