on: [push, pull_request]

jobs:
  unit:
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu", "windows", "macos" ]
        go: [ "1.14.x", "1.15.x", "1.16.0-rc1" ]
    runs-on: ${{ matrix.os }}-latest
    name: Unit tests (${{ matrix.os}}, Go ${{ matrix.go }})
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: '!contains(${{ matrix.go }}, "beta") && !contains(${{ matrix.go }}, "rc")'
          go-version: ${{ matrix.go }}
      - run: go version
      - name: Install test tools
        run: |
          go get golang.org/x/tools/cmd/cover
          go get github.com/onsi/ginkgo/ginkgo
          go get github.com/onsi/gomega
      - name: Install dependencies
        run: go build
      - name: Run tests
        run: ginkgo -r -v -cover -randomizeAllSpecs -randomizeSuites -trace
      - name: Run tests (32 bit)
        if: ${{ matrix.os != 'macos' }} # can't run 32 bit tests on OSX.
        env:
          GOARCH: 386
        run: ginkgo -r -v -cover -coverprofile coverage.txt -outputdir . -randomizeAllSpecs -randomizeSuites -trace
      - name: Run tests with race detector
        if: ${{ matrix.os == 'ubuntu' }} # speed things up. Windows and OSX VMs are slow
        run: ginkgo -r -v -race -randomizeAllSpecs -randomizeSuites -trace
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: coverage.txt
          env_vars: OS=${{ matrix.os }}, GO=${{ matrix.go }}
